
// Auto-generated module file for TensorBoard protobuf bindings
// This file is generated by build.rs - do not edit manually
        


#[path = "google.protobuf.rs"]
mod google_protobuf;

pub mod google {
    pub mod protobuf {
        pub use super::super::google_protobuf::*;
    }
}
            


#[path = "tensorboard.rs"]
pub mod tensorboard;
            

