[package]
name = "tetris-search"
version = "0.1.0"
edition = "2024"
authors = ["Alex Comerford <alex@taoa.io>"]
publish = false
description = "Search algorithms for Tetris (beam search, state space exploration)"

[lib]
name = "tetris_search"
path = "src/lib.rs"

[features]
default = []
never-inline = []

[dependencies]
tetris-game.workspace = true
tetris-utils.workspace = true
proc-macros.workspace = true
rayon.workspace = true
rand.workspace = true
num_cpus.workspace = true

[lints]
workspace = true
