[package]
name = "tensorboard"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
prost.workspace = true
prost-types.workspace = true
image.workspace = true
gethostname.workspace = true
crc32fast = "1.4.2"

[build-dependencies]
prost-build = "0.13"

[lib]
name = "tensorboard"
path = "src/lib.rs"
doctest = false
