import Mathlib
import Proofs.Game

/-!
# Survival framework

The vocabulary for any survivability claim:

* `Policy cfg` — a function `GameState → Placement`.
* `trace cfg π g0 : ℕ → GameState` — the infinite trace from `g0` under `π`.
* `SurvivesForever cfg π g0` — the policy never tops out from `g0`.
* `safe_invariant` — the universal proof template: any policy that preserves a
  loss-avoiding invariant survives forever.
* `ClosedCycle cfg` — a finite set of states with a policy that keeps you in it,
  legally and without losing. This is the M2/M3 artifact.
* `closed_cycle_survives` — entering a closed cycle implies infinite play.
-/

namespace Tetris

/-- A policy chooses a placement from any game state. -/
abbrev Policy (_cfg : GameConfig) := GameState → Placement

/-- The state trace generated by following policy `π` from initial state `g0`. -/
def trace (cfg : GameConfig) (π : Policy cfg) (g0 : GameState) : ℕ → GameState
  | 0     => g0
  | n + 1 =>
      let g := trace cfg π g0 n
      g.step cfg (π g)

@[simp] theorem trace_zero (cfg : GameConfig) (π : Policy cfg) (g0 : GameState) :
    trace cfg π g0 0 = g0 := rfl

theorem trace_succ (cfg : GameConfig) (π : Policy cfg) (g0 : GameState) (n : ℕ) :
    trace cfg π g0 (n + 1) =
      (trace cfg π g0 n).step cfg (π (trace cfg π g0 n)) := rfl

/-- The first step of a trace. -/
theorem trace_one (cfg : GameConfig) (π : Policy cfg) (g0 : GameState) :
    trace cfg π g0 1 = g0.step cfg (π g0) := by
  rw [trace_succ, trace_zero]

/-- The second step of a trace. -/
theorem trace_two (cfg : GameConfig) (π : Policy cfg) (g0 : GameState) :
    trace cfg π g0 2 =
      (g0.step cfg (π g0)).step cfg (π (g0.step cfg (π g0))) := by
  rw [show (2 : ℕ) = 1 + 1 from rfl, trace_succ, trace_one]

/-- The trace from `init` at index 0 is `init`. -/
@[simp] theorem trace_init_zero (cfg : GameConfig) (π : Policy cfg) :
    trace cfg π GameState.init 0 = GameState.init := trace_zero cfg π GameState.init

/-- The trace from `init` at index 1 is `init.step cfg (π init)`. -/
theorem trace_init_one (cfg : GameConfig) (π : Policy cfg) :
    trace cfg π GameState.init 1 = GameState.init.step cfg (π GameState.init) :=
  trace_one cfg π GameState.init

/-- The trace from `init` at index 2 is two-step from `init`. -/
theorem trace_init_two (cfg : GameConfig) (π : Policy cfg) :
    trace cfg π GameState.init 2 =
      (GameState.init.step cfg (π GameState.init)).step cfg
        (π (GameState.init.step cfg (π GameState.init))) :=
  trace_two cfg π GameState.init

/-- The trace from `init` always satisfies `trace_zero_eq_init`: at 0 it's
exactly `init` (rewrite-friendly). -/
@[simp] theorem trace_init_eq_init_iff (cfg : GameConfig) (π : Policy cfg) {n : ℕ}
    (hn : n = 0) : trace cfg π GameState.init n = GameState.init := by
  subst hn; rfl


/-- `trace cfg π g0 3 = trace cfg π g0 2 |>.step cfg (π _)` (the third step). -/
theorem trace_three (cfg : GameConfig) (π : Policy cfg) (g0 : GameState) :
    trace cfg π g0 3 =
      (trace cfg π g0 2).step cfg (π (trace cfg π g0 2)) :=
  trace_succ cfg π g0 2

/-- Splitting a trace: `trace cfg π g0 (n + m) = trace cfg π (trace cfg π g0 n) m`. -/
theorem trace_add (cfg : GameConfig) (π : Policy cfg) (g0 : GameState) (n m : ℕ) :
    trace cfg π g0 (n + m) = trace cfg π (trace cfg π g0 n) m := by
  induction m with
  | zero => rw [Nat.add_zero, trace_zero]
  | succ k ih =>
    rw [show n + (k + 1) = (n + k) + 1 from by omega, trace_succ, trace_succ, ih]


/-- **Trace is determined by its current state**: if two trace indices
have equal state, then their `k`-step continuations also coincide. The
foundation of trace periodicity: the recurrence is deterministic. -/
theorem trace_eq_of_state_eq {cfg : GameConfig} (π : Policy cfg)
    (g0 : GameState) {n m : ℕ}
    (h : trace cfg π g0 n = trace cfg π g0 m) (k : ℕ) :
    trace cfg π g0 (n + k) = trace cfg π g0 (m + k) := by
  induction k with
  | zero => exact h
  | succ k' ih =>
    rw [show n + (k' + 1) = (n + k') + 1 from by omega,
        show m + (k' + 1) = (m + k') + 1 from by omega,
        trace_succ, trace_succ, ih]

/-- A policy survives forever from `g0`: the trace never lands in a lost state. -/
def SurvivesForever (cfg : GameConfig) (π : Policy cfg) (g0 : GameState) : Prop :=
  ∀ n, ¬ (trace cfg π g0 n).lost cfg

/-- The initial state is not lost. -/
theorem SurvivesForever.not_lost {cfg : GameConfig} {π : Policy cfg}
    {g0 : GameState} (h : SurvivesForever cfg π g0) : ¬ g0.lost cfg := by
  have := h 0
  simpa using this

/-- The trace state at index `n` is not lost. -/
theorem SurvivesForever.trace_not_lost {cfg : GameConfig} {π : Policy cfg}
    {g0 : GameState} (h : SurvivesForever cfg π g0) (n : ℕ) :
    ¬ (trace cfg π g0 n).lost cfg := h n

/-- If a policy survives forever from `g0`, it also survives forever from
the post-step state. -/
theorem SurvivesForever.step {cfg : GameConfig} {π : Policy cfg}
    {g0 : GameState} (h : SurvivesForever cfg π g0) :
    SurvivesForever cfg π (g0.step cfg (π g0)) := by
  intro n
  have h' := h (1 + n)
  rw [trace_add, trace_one] at h'
  exact h'

/-- If a policy survives forever from `g0`, it also survives forever from
any trace state along the way. -/
theorem SurvivesForever.from_trace {cfg : GameConfig} {π : Policy cfg}
    {g0 : GameState} (h : SurvivesForever cfg π g0) (k : ℕ) :
    SurvivesForever cfg π (trace cfg π g0 k) := by
  intro n
  rw [← trace_add]
  exact h (k + n)

/-- A policy fails to survive forever if any trace state is lost. -/
theorem not_SurvivesForever_of_trace_lost {cfg : GameConfig} {π : Policy cfg}
    {g0 : GameState} {n : ℕ} (h : (trace cfg π g0 n).lost cfg) :
    ¬ SurvivesForever cfg π g0 :=
  fun hsf => hsf n h

/-- Definitional unfolding: `SurvivesForever` is `∀ n, ¬ trace n.lost`. -/
theorem SurvivesForever_iff_forall_trace_not_lost (cfg : GameConfig)
    (π : Policy cfg) (g0 : GameState) :
    SurvivesForever cfg π g0 ↔ ∀ n, ¬ (trace cfg π g0 n).lost cfg :=
  Iff.rfl

/-- `SurvivesForever` is equivalent to "no trace state is lost". -/
theorem SurvivesForever_iff_not_exists_trace_lost (cfg : GameConfig)
    (π : Policy cfg) (g0 : GameState) :
    SurvivesForever cfg π g0 ↔ ¬ ∃ n, (trace cfg π g0 n).lost cfg := by
  rw [SurvivesForever_iff_forall_trace_not_lost]
  exact ⟨fun h ⟨n, hn⟩ => h n hn, fun h n hn => h ⟨n, hn⟩⟩

/-- `¬ SurvivesForever` characterised by existence of a lost trace state. -/
theorem not_SurvivesForever_iff_exists_trace_lost (cfg : GameConfig)
    (π : Policy cfg) (g0 : GameState) :
    ¬ SurvivesForever cfg π g0 ↔ ∃ n, (trace cfg π g0 n).lost cfg := by
  rw [SurvivesForever_iff_not_exists_trace_lost, not_not]

/-- **The universal survivability template.** If a state predicate `I` holds at
`g0`, is preserved by the policy, and forbids loss, then the policy survives
forever from `g0`. Every survival proof in this codebase will be an instance of
this lemma. -/
theorem safe_invariant {cfg : GameConfig} {π : Policy cfg} {g0 : GameState}
    (I : GameState → Prop)
    (h0 : I g0)
    (hpres : ∀ g, I g → I (g.step cfg (π g)))
    (hsafe : ∀ g, I g → ¬ g.lost cfg) :
    SurvivesForever cfg π g0 := by
  intro n
  suffices h : I (trace cfg π g0 n) from hsafe _ h
  induction n with
  | zero => exact h0
  | succ k ih =>
      rw [trace_succ]
      exact hpres _ ih

/-- A **closed cycle**: a finite set of states with a policy that keeps every
move bag-legal, in-bounds, non-losing, and inside the set. Any closed cycle is
an infinite-play certificate for its member states (see `closed_cycle_survives`).
This is the M2/M3 artifact of the project mission. -/
structure ClosedCycle (cfg : GameConfig) where
  /-- The states in the cycle. -/
  states : Finset GameState
  /-- The policy used inside the cycle. -/
  policy : Policy cfg
  /-- Each placement is in-bounds for the configured columns. -/
  valid : ∀ s ∈ states, (policy s).Valid cfg
  /-- The drawn piece is in the current bag. -/
  legal_draw : ∀ s ∈ states, s.bag.canDraw (policy s).piece
  /-- No state in the cycle is lost. -/
  not_lost : ∀ s ∈ states, ¬ s.lost cfg
  /-- Stepping under the policy keeps you in the cycle. -/
  closed : ∀ s ∈ states, (s.step cfg (policy s)) ∈ states

/-- **A closed cycle is an infinite-play certificate.** Starting from any state
in the cycle, following the cycle's policy survives forever — because the cycle
membership is itself a `safe_invariant`. This is the local-to-global principle
the Atlas mission rests on. -/
theorem closed_cycle_survives {cfg : GameConfig} (C : ClosedCycle cfg)
    {g0 : GameState} (h0 : g0 ∈ C.states) :
    SurvivesForever cfg C.policy g0 :=
  safe_invariant (I := fun s => s ∈ C.states) h0
    (fun g hg => C.closed g hg)
    (fun g hg => C.not_lost g hg)

/-- Dot form of `closed_cycle_survives`. -/
theorem ClosedCycle.survives {cfg : GameConfig} (C : ClosedCycle cfg)
    {g0 : GameState} (h0 : g0 ∈ C.states) :
    SurvivesForever cfg C.policy g0 :=
  closed_cycle_survives C h0

/-- Init in cycle ⇒ cycle policy survives from init. -/
theorem ClosedCycle.init_survives {cfg : GameConfig} (C : ClosedCycle cfg)
    (h : GameState.init ∈ C.states) :
    SurvivesForever cfg C.policy GameState.init :=
  C.survives h

/-- Init in cycle ⇒ existence of a policy that survives forever
from init. Packaged existence form. -/
theorem ClosedCycle.exists_survivesForever_of_init_mem {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : GameState.init ∈ C.states) :
    ∃ π : Policy cfg, SurvivesForever cfg π GameState.init :=
  ⟨C.policy, C.init_survives h⟩

/-- **Summary**: existence of a closed cycle through init implies
existence of an init-surviving policy. The user-facing M3 shape:
`(∃ C, init ∈ C.states) → (∃ π, SurvivesForever π init)`. -/
theorem exists_survivesForever_of_exists_init_cycle {cfg : GameConfig}
    (h : ∃ C : ClosedCycle cfg, GameState.init ∈ C.states) :
    ∃ π : Policy cfg, SurvivesForever cfg π GameState.init := by
  obtain ⟨C, hC⟩ := h
  exact C.exists_survivesForever_of_init_mem hC

/-- Contrapositive: if no policy survives forever from init, then
no closed cycle through init can exist. -/
theorem not_exists_init_cycle_of_not_exists_survivesForever {cfg : GameConfig}
    (h : ¬ ∃ π : Policy cfg, SurvivesForever cfg π GameState.init) :
    ¬ ∃ C : ClosedCycle cfg, GameState.init ∈ C.states :=
  fun hC => h (exists_survivesForever_of_exists_init_cycle hC)

/-- For any cycle state, its successor is also not lost (since
the successor lands in `C.states` and the closure invariant gives
not-lost). -/
theorem ClosedCycle.step_not_lost {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) :
    ¬ (g.step cfg (C.policy g)).lost cfg :=
  C.not_lost _ (C.closed g hg)

/-- The policy's placement at any successor state is also valid. -/
theorem ClosedCycle.step_policy_valid {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) :
    (C.policy (g.step cfg (C.policy g))).Valid cfg :=
  C.valid _ (C.closed g hg)

/-- The successor state's bag can draw the policy's chosen piece. -/
theorem ClosedCycle.step_legal_draw {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) :
    (g.step cfg (C.policy g)).bag.canDraw
      (C.policy (g.step cfg (C.policy g))).piece :=
  C.legal_draw _ (C.closed g hg)

/-- Two steps from a cycle state still land in the cycle. -/
theorem ClosedCycle.step_step_mem {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) :
    (g.step cfg (C.policy g)).step cfg
      (C.policy (g.step cfg (C.policy g))) ∈ C.states :=
  C.closed _ (C.closed g hg)


/-- **Every trace state from inside a closed cycle stays inside.** Induction
on the trace step count: the closed-under-policy invariant propagates. -/
theorem ClosedCycle.trace_mem_states {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states)
    (n : ℕ) : trace cfg C.policy g0 n ∈ C.states := by
  induction n with
  | zero => exact h0
  | succ k ih => rw [trace_succ]; exact C.closed _ ih

/-- **Every trace state from inside a closed cycle is non-lost.** Direct
corollary of `trace_mem_states` + `not_lost`. -/
theorem ClosedCycle.trace_not_lost {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states)
    (n : ℕ) : ¬ (trace cfg C.policy g0 n).lost cfg :=
  C.not_lost _ (C.trace_mem_states h0 n)

/-- At any trace step, the policy's chosen piece is drawable from
the trace state's bag. Trace-level lift of `legal_draw`. -/
theorem ClosedCycle.trace_legal_draw {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states)
    (n : ℕ) :
    (trace cfg C.policy g0 n).bag.canDraw
      (C.policy (trace cfg C.policy g0 n)).piece :=
  C.legal_draw _ (C.trace_mem_states h0 n)

/-- At any trace step, the policy's placement is valid. -/
theorem ClosedCycle.trace_policy_valid {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states)
    (n : ℕ) :
    (C.policy (trace cfg C.policy g0 n)).Valid cfg :=
  C.valid _ (C.trace_mem_states h0 n)

/-- The `(n+1)`-th trace state is in `C.states` (succ form). -/
theorem ClosedCycle.trace_succ_mem_states {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states)
    (n : ℕ) : trace cfg C.policy g0 (n + 1) ∈ C.states :=
  C.trace_mem_states h0 (n + 1)

/-- The `(n+1)`-th trace state is `step` of the `n`-th: lifted
form of `trace_succ` to the `ClosedCycle.policy` setting. -/
theorem ClosedCycle.trace_succ_eq {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    trace cfg C.policy g0 (n + 1) =
      (trace cfg C.policy g0 n).step cfg
        (C.policy (trace cfg C.policy g0 n)) :=
  trace_succ cfg C.policy g0 n

/-- The zeroth trace state is the seed. -/
@[simp] theorem ClosedCycle.trace_zero_eq {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) :
    trace cfg C.policy g0 0 = g0 :=
  trace_zero cfg C.policy g0

/-- The first trace state under a cycle policy. -/
theorem ClosedCycle.trace_one_eq {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) :
    trace cfg C.policy g0 1 = g0.step cfg (C.policy g0) :=
  trace_one cfg C.policy g0

/-- A cycle trace step splits via `trace_add`. -/
theorem ClosedCycle.trace_add {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n m : ℕ) :
    trace cfg C.policy g0 (n + m) = trace cfg C.policy (trace cfg C.policy g0 n) m :=
  Tetris.trace_add cfg C.policy g0 n m

/-- The second trace state under a cycle policy. -/
theorem ClosedCycle.trace_two_eq {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) :
    trace cfg C.policy g0 2 =
      (g0.step cfg (C.policy g0)).step cfg
        (C.policy (g0.step cfg (C.policy g0))) :=
  trace_two cfg C.policy g0

/-- The 0-th cycle trace state at `init` is `init`. -/
@[simp] theorem ClosedCycle.trace_init_zero {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    trace cfg C.policy GameState.init 0 = GameState.init :=
  Tetris.trace_init_zero cfg C.policy

/-- The 1st cycle trace state at `init`. -/
theorem ClosedCycle.trace_init_one {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    trace cfg C.policy GameState.init 1 =
      GameState.init.step cfg (C.policy GameState.init) :=
  Tetris.trace_init_one cfg C.policy

/-- The 2nd cycle trace state at `init`. -/
theorem ClosedCycle.trace_init_two {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    trace cfg C.policy GameState.init 2 =
      (GameState.init.step cfg (C.policy GameState.init)).step cfg
        (C.policy (GameState.init.step cfg (C.policy GameState.init))) :=
  Tetris.trace_init_two cfg C.policy

/-- Seeded at a cycle state, the zeroth trace state is in `C.states`. -/
theorem ClosedCycle.trace_zero_mem_states {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    trace cfg C.policy g0 0 ∈ C.states := by
  rw [C.trace_zero_eq]; exact h0

/-- Seeded at a non-lost cycle state, the zeroth trace state is not lost. -/
theorem ClosedCycle.trace_zero_not_lost {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (hnl : ¬ g0.lost cfg) :
    ¬ (trace cfg C.policy g0 0).lost cfg := by
  rw [C.trace_zero_eq]; exact hnl

/-- The zeroth trace state has the same bag as the seed. -/
@[simp] theorem ClosedCycle.trace_zero_bag {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) :
    (trace cfg C.policy g0 0).bag = g0.bag := by
  rw [C.trace_zero_eq]

/-- The zeroth trace state has the same board as the seed. -/
@[simp] theorem ClosedCycle.trace_zero_board {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) :
    (trace cfg C.policy g0 0).board = g0.board := by
  rw [C.trace_zero_eq]

/-- Init-seeded zeroth-trace board is `Board.empty`. -/
@[simp] theorem ClosedCycle.init_trace_zero_board {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    (trace cfg C.policy GameState.init 0).board = Board.empty := by
  rw [C.trace_zero_board, GameState.init_board]

/-- Init-seeded zeroth-trace bag is `Bag.full`. -/
@[simp] theorem ClosedCycle.init_trace_zero_bag {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    (trace cfg C.policy GameState.init 0).bag = Bag.full := by
  rw [C.trace_zero_bag, GameState.init_bag]

/-- Init-seeded zeroth-trace state equals `init`. -/
@[simp] theorem ClosedCycle.init_trace_zero_eq_init {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    trace cfg C.policy GameState.init 0 = GameState.init :=
  C.trace_zero_eq GameState.init

/-- Init-seeded zeroth-trace state is not lost. -/
theorem ClosedCycle.init_trace_zero_not_lost {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    ¬ (trace cfg C.policy GameState.init 0).lost cfg :=
  C.trace_zero_not_lost (GameState.init_not_lost cfg)

/-- If `init ∈ C.states`, the init-seeded zeroth-trace state is in `C.states`. -/
theorem ClosedCycle.init_trace_zero_mem_states {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : GameState.init ∈ C.states) :
    trace cfg C.policy GameState.init 0 ∈ C.states :=
  C.trace_zero_mem_states h

/-- Successor trace bag is the post-step draw bag. -/
theorem ClosedCycle.trace_succ_bag {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 (n + 1)).bag =
      (trace cfg C.policy g0 n).bag.draw
        (C.policy (trace cfg C.policy g0 n)).piece := by
  rw [C.trace_succ_eq]; rfl

/-- Successor trace board is the post-step applied board. -/
theorem ClosedCycle.trace_succ_board {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 (n + 1)).board =
      Placement.applyStep cfg (trace cfg C.policy g0 n).board
        (C.policy (trace cfg C.policy g0 n)) := by
  rw [C.trace_succ_eq]; rfl

/-- Successor trace bag is nonempty (`draw` always yields a nonempty bag). -/
theorem ClosedCycle.trace_succ_bag_nonempty {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 (n + 1)).bag.Nonempty := by
  rw [C.trace_succ_bag]; exact Bag.draw_nonempty _ _

/-- Successor trace bag is `≠ ∅`. -/
theorem ClosedCycle.trace_succ_bag_ne_empty {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 (n + 1)).bag ≠ ∅ :=
  (C.trace_succ_bag_nonempty g0 n).ne_empty

/-- Successor trace bag has positive card. -/
theorem ClosedCycle.trace_succ_bag_card_pos {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    0 < (trace cfg C.policy g0 (n + 1)).bag.card :=
  Finset.card_pos.mpr (C.trace_succ_bag_nonempty g0 n)

/-- Successor trace bag has card `≤ 7`. -/
theorem ClosedCycle.trace_succ_bag_card_le_seven {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 (n + 1)).bag.card ≤ 7 :=
  Bag.card_le_seven _

/-- Successor trace bag has card in `[1, 7]`. -/
theorem ClosedCycle.trace_succ_bag_card_interval {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    1 ≤ (trace cfg C.policy g0 (n + 1)).bag.card ∧
      (trace cfg C.policy g0 (n + 1)).bag.card ≤ 7 :=
  ⟨C.trace_succ_bag_card_pos g0 n, C.trace_succ_bag_card_le_seven g0 n⟩

/-- Successor trace bag is a subset of `Bag.full`. -/
theorem ClosedCycle.trace_succ_bag_subset_full {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 (n + 1)).bag ⊆ Bag.full :=
  Bag.subset_full _

/-- Any trace bag (all n) is a subset of `Bag.full`. -/
theorem ClosedCycle.trace_bag_subset_full {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 n).bag ⊆ Bag.full :=
  Bag.subset_full _

/-- Any trace bag (all n) has card `≤ 7`. -/
theorem ClosedCycle.trace_bag_card_le_seven {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 n).bag.card ≤ 7 :=
  Bag.card_le_seven _

/-- Any trace bag (all n) has card `< 8`. -/
theorem ClosedCycle.trace_bag_card_lt_eight {cfg : GameConfig}
    (C : ClosedCycle cfg) (g0 : GameState) (n : ℕ) :
    (trace cfg C.policy g0 n).bag.card < 8 :=
  Nat.lt_succ_of_le (C.trace_bag_card_le_seven g0 n)

/-- For a seed with nonempty bag, every trace state has nonempty bag. -/
theorem ClosedCycle.trace_bag_nonempty_of_seed_bag_nonempty
    {cfg : GameConfig} (C : ClosedCycle cfg) {g0 : GameState}
    (h0 : g0.bag.Nonempty) (n : ℕ) :
    (trace cfg C.policy g0 n).bag.Nonempty := by
  rcases n with _ | n
  · rw [C.trace_zero_bag]; exact h0
  · exact C.trace_succ_bag_nonempty g0 n

/-- For a seed with nonempty bag, every trace state has positive bag card. -/
theorem ClosedCycle.trace_bag_card_pos_of_seed_bag_nonempty
    {cfg : GameConfig} (C : ClosedCycle cfg) {g0 : GameState}
    (h0 : g0.bag.Nonempty) (n : ℕ) :
    0 < (trace cfg C.policy g0 n).bag.card :=
  Finset.card_pos.mpr (C.trace_bag_nonempty_of_seed_bag_nonempty h0 n)

/-- For a seed with nonempty bag, every trace state has `≠ ∅` bag. -/
theorem ClosedCycle.trace_bag_ne_empty_of_seed_bag_nonempty
    {cfg : GameConfig} (C : ClosedCycle cfg) {g0 : GameState}
    (h0 : g0.bag.Nonempty) (n : ℕ) :
    (trace cfg C.policy g0 n).bag ≠ ∅ :=
  (C.trace_bag_nonempty_of_seed_bag_nonempty h0 n).ne_empty

/-- Init-seeded trace bag is always nonempty (init.bag = Bag.full is nonempty). -/
theorem ClosedCycle.init_trace_bag_nonempty {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    (trace cfg C.policy GameState.init n).bag.Nonempty :=
  C.trace_bag_nonempty_of_seed_bag_nonempty
    (GameState.init_bag.symm ▸ Bag.full_nonempty) n

/-- Init-seeded trace bag has positive card. -/
theorem ClosedCycle.init_trace_bag_card_pos {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    0 < (trace cfg C.policy GameState.init n).bag.card :=
  Finset.card_pos.mpr (C.init_trace_bag_nonempty n)

/-- Init-seeded trace bag is `≠ ∅`. -/
theorem ClosedCycle.init_trace_bag_ne_empty {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    (trace cfg C.policy GameState.init n).bag ≠ ∅ :=
  (C.init_trace_bag_nonempty n).ne_empty

/-- Init-seeded trace bag has card in `[1, 7]`. -/
theorem ClosedCycle.init_trace_bag_card_interval {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    1 ≤ (trace cfg C.policy GameState.init n).bag.card ∧
      (trace cfg C.policy GameState.init n).bag.card ≤ 7 :=
  ⟨C.init_trace_bag_card_pos n, C.trace_bag_card_le_seven _ n⟩

/-- Init-seeded trace bag has card `≥ 1`. -/
theorem ClosedCycle.init_trace_bag_card_ge_one {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    1 ≤ (trace cfg C.policy GameState.init n).bag.card :=
  C.init_trace_bag_card_pos n

/-- Init-seeded trace bag has card `≤ 7`. -/
theorem ClosedCycle.init_trace_bag_card_le_seven {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    (trace cfg C.policy GameState.init n).bag.card ≤ 7 :=
  C.trace_bag_card_le_seven _ n

/-- Init-seeded trace bag has `card ≠ 0`. -/
theorem ClosedCycle.init_trace_bag_card_ne_zero {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    (trace cfg C.policy GameState.init n).bag.card ≠ 0 :=
  Nat.ne_of_gt (C.init_trace_bag_card_pos n)

/-- Init-seeded trace bag has card `< 8`. -/
theorem ClosedCycle.init_trace_bag_card_lt_eight {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    (trace cfg C.policy GameState.init n).bag.card < 8 :=
  C.trace_bag_card_lt_eight _ n

/-- Init-seeded trace bag ⊆ `Bag.full`. -/
theorem ClosedCycle.init_trace_bag_subset_full {cfg : GameConfig}
    (C : ClosedCycle cfg) (n : ℕ) :
    (trace cfg C.policy GameState.init n).bag ⊆ Bag.full :=
  C.trace_bag_subset_full _ n

/-- The zeroth init-seeded trace state has `bag.card = 7`. -/
@[simp] theorem ClosedCycle.init_trace_zero_bag_card {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    (trace cfg C.policy GameState.init 0).bag.card = 7 := by
  rw [C.init_trace_zero_bag]; exact Bag.full_card

/-- The zeroth init-seeded trace state has `board.count = 0`. -/
@[simp] theorem ClosedCycle.init_trace_zero_board_count {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    (trace cfg C.policy GameState.init 0).board.count = 0 := by
  rw [C.init_trace_zero_board]; rfl

/-- The zeroth init-seeded trace state has empty board (Nonempty negation). -/
theorem ClosedCycle.init_trace_zero_board_not_nonempty {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    ¬ (trace cfg C.policy GameState.init 0).board.Nonempty := by
  rw [C.init_trace_zero_board]; exact Finset.not_nonempty_empty

/-- The zeroth init-seeded trace state is `Reachable`. -/
theorem ClosedCycle.init_trace_zero_reachable {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    Reachable cfg (trace cfg C.policy GameState.init 0) := by
  rw [C.init_trace_zero_eq_init]; exact Reachable.of_init

/-- Every init-seeded trace state is `Reachable`. Inductive lift using
`trace_policy_valid`, `trace_legal_draw`, `trace_not_lost`. -/
theorem ClosedCycle.init_trace_reachable {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : GameState.init ∈ C.states) (n : ℕ) :
    Reachable cfg (trace cfg C.policy GameState.init n) := by
  induction n with
  | zero => exact C.init_trace_zero_reachable
  | succ k ih =>
    rw [trace_succ]
    exact ih.step (C.trace_legal_draw h k)
      (C.trace_policy_valid h k) (C.trace_not_lost h k)

/-- Generalised: starting from any Reachable seed inside the cycle, every
trace state is Reachable. -/
theorem ClosedCycle.trace_reachable {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states)
    (hr : Reachable cfg g0) (n : ℕ) :
    Reachable cfg (trace cfg C.policy g0 n) := by
  induction n with
  | zero => rw [C.trace_zero_eq]; exact hr
  | succ k ih =>
    rw [trace_succ]
    exact ih.step (C.trace_legal_draw h0 k)
      (C.trace_policy_valid h0 k) (C.trace_not_lost h0 k)

/-- Every init-seeded trace state has a well-formed board. -/
theorem ClosedCycle.init_trace_wf {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : GameState.init ∈ C.states) (n : ℕ) :
    Board.WF cfg (trace cfg C.policy GameState.init n).board :=
  (C.init_trace_reachable h n).wf

/-- Generalised: any Reachable-seeded trace state has a WF board. -/
theorem ClosedCycle.trace_wf {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states)
    (hr : Reachable cfg g0) (n : ℕ) :
    Board.WF cfg (trace cfg C.policy g0 n).board :=
  (C.trace_reachable h0 hr n).wf

/-- Every init-seeded trace state is `Reachable` and not lost — bundled. -/
theorem ClosedCycle.init_trace_reachable_and_not_lost {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : GameState.init ∈ C.states) (n : ℕ) :
    Reachable cfg (trace cfg C.policy GameState.init n) ∧
      ¬ (trace cfg C.policy GameState.init n).lost cfg :=
  ⟨C.init_trace_reachable h n, C.trace_not_lost h n⟩

/-- Every cycle state has a nonempty bag. The policy's piece is
drawable (legal_draw), so the bag contains it. -/
theorem ClosedCycle.bag_nonempty {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) : g.bag.Nonempty :=
  ⟨_, C.legal_draw g hg⟩

theorem ClosedCycle.bag_card_pos {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) : 0 < g.bag.card :=
  Finset.card_pos.mpr (C.bag_nonempty hg)

theorem ClosedCycle.bag_ne_empty {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) : g.bag ≠ ∅ :=
  (C.bag_nonempty hg).ne_empty

theorem ClosedCycle.bag_card_ne_zero {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) : g.bag.card ≠ 0 :=
  Nat.ne_of_gt (C.bag_card_pos hg)

theorem ClosedCycle.bag_card_ge_one {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) : 1 ≤ g.bag.card :=
  C.bag_card_pos hg

/-- `Bag.full` has card 7, so any bag has card ≤ 7 (regardless of
cycle membership — but this gives the dot accessor). -/
theorem ClosedCycle.bag_card_le_seven {cfg : GameConfig} (_C : ClosedCycle cfg)
    {g : GameState} (_hg : g ∈ _C.states) : g.bag.card ≤ 7 :=
  Bag.card_le_seven _

/-- Bundled `[1, 7]` bag-card interval at any cycle state. -/
theorem ClosedCycle.bag_card_interval {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) :
    1 ≤ g.bag.card ∧ g.bag.card ≤ 7 :=
  ⟨C.bag_card_ge_one hg, C.bag_card_le_seven hg⟩

/-- Any cycle state's bag is a subset of the full bag (always
true since `Bag.full` is the universe; dot accessor). -/
theorem ClosedCycle.bag_subset_full {cfg : GameConfig} (_C : ClosedCycle cfg)
    {g : GameState} (_hg : g ∈ _C.states) : g.bag ⊆ Bag.full :=
  Bag.subset_full _

/-- Strict `< 8` bag-card form at any cycle state. -/
theorem ClosedCycle.bag_card_lt_eight {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) : g.bag.card < 8 := by
  have := C.bag_card_le_seven hg
  omega

/-- Cycle-state bag is either full or has card ≤ 6. -/
theorem ClosedCycle.bag_eq_full_or_card_le_six {cfg : GameConfig}
    (_C : ClosedCycle cfg) {g : GameState} (_hg : g ∈ _C.states) :
    g.bag = Bag.full ∨ g.bag.card ≤ 6 :=
  Bag.eq_full_or_card_le_six _

/-- **The first `n+1` distinct trace states from inside a closed cycle
sit inside the cycle's `states` Finset.** Card form: the image's size
is bounded by `C.states.card`. -/
theorem ClosedCycle.trace_image_subset_states {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states)
    (n : ℕ) :
    ((Finset.range (n + 1)).image
        (fun k => trace cfg C.policy g0 k)) ⊆ C.states := by
  intro g hg
  rw [Finset.mem_image] at hg
  obtain ⟨k, _, rfl⟩ := hg
  exact C.trace_mem_states h0 k

/-- **Pigeonhole on trace through a closed cycle**: a trace of length
`> C.states.card` from any cycle entry must revisit some state.
Provides two distinct indices `i ≠ j` in `[0, C.states.card]` with
matching trace states. -/
theorem ClosedCycle.trace_pigeonhole {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    ∃ i j : ℕ, i ≤ C.states.card ∧ j ≤ C.states.card ∧ i ≠ j ∧
      trace cfg C.policy g0 i = trace cfg C.policy g0 j := by
  have hmap : ∀ k ∈ Finset.range (C.states.card + 1),
      trace cfg C.policy g0 k ∈ C.states :=
    fun k _ => C.trace_mem_states h0 k
  have hcard : C.states.card < (Finset.range (C.states.card + 1)).card := by
    rw [Finset.card_range]; omega
  obtain ⟨i, hi, j, hj, hne, heq⟩ :=
    Finset.exists_ne_map_eq_of_card_lt_of_maps_to hcard hmap
  rw [Finset.mem_range] at hi hj
  exact ⟨i, j, by omega, by omega, hne, heq⟩

/-- **Ordered pigeonhole**: same as Tick 335 but the two indices are
strictly ordered (`i < j`). Useful for cycle-length / period arguments
where the *gap* `j - i` is the loop length. -/
theorem ClosedCycle.trace_pigeonhole_lt {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    ∃ i j : ℕ, i < j ∧ j ≤ C.states.card ∧
      trace cfg C.policy g0 i = trace cfg C.policy g0 j := by
  obtain ⟨i, j, hi, hj, hne, heq⟩ := C.trace_pigeonhole h0
  rcases lt_or_gt_of_ne hne with h | h
  · exact ⟨i, j, h, hj, heq⟩
  · exact ⟨j, i, h, hi, heq.symm⟩

/-- **Explicit period extraction**: from Tick 336 there exist a base
index `i` and a positive period `d ≤ C.states.card` such that
`trace_i = trace_(i+d)`. The cycle's policy repeats with period at
most `|states|`. -/
theorem ClosedCycle.trace_exists_period {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    ∃ i d : ℕ, 0 < d ∧ d ≤ C.states.card ∧
      trace cfg C.policy g0 i = trace cfg C.policy g0 (i + d) := by
  obtain ⟨i, j, hlt, hj, heq⟩ := C.trace_pigeonhole_lt h0
  refine ⟨i, j - i, ?_, ?_, ?_⟩
  · omega
  · omega
  · rw [show i + (j - i) = j from by omega]; exact heq

/-- **`trace_exists_period` with base-state-in-cycle**: companion to
`trace_exists_period` witnessing the base state lies in `C.states`. -/
theorem ClosedCycle.trace_exists_period_in_states {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    ∃ i d : ℕ, 0 < d ∧ d ≤ C.states.card ∧
      trace cfg C.policy g0 i = trace cfg C.policy g0 (i + d) ∧
      trace cfg C.policy g0 i ∈ C.states := by
  obtain ⟨i, d, hpos, hle, heq⟩ := C.trace_exists_period h0
  exact ⟨i, d, hpos, hle, heq, C.trace_mem_states h0 i⟩

/-- **From-trace survival iff**: `SurvivesForever cfg π (trace cfg π g₀ k)`
is equivalent to `∀ m ≥ k, ¬ (trace cfg π g₀ m).lost cfg`. -/
theorem SurvivesForever_trace_iff_forall_ge_not_lost {cfg : GameConfig}
    {π : Policy cfg} {g0 : GameState} {k : ℕ} :
    SurvivesForever cfg π (trace cfg π g0 k) ↔
      ∀ m, k ≤ m → ¬ (trace cfg π g0 m).lost cfg := by
  refine ⟨fun h m hkm => ?_, fun h n => ?_⟩
  · obtain ⟨j, rfl⟩ := Nat.exists_eq_add_of_le hkm
    rw [trace_add]; exact h j
  · rw [← trace_add]; exact h (k + n) (by omega)

/-- **Negation form**: `¬ SurvivesForever cfg π (trace cfg π g₀ k)` iff
some index `m ≥ k` is lost. -/
theorem not_SurvivesForever_trace_iff_exists_ge_lost {cfg : GameConfig}
    {π : Policy cfg} {g0 : GameState} {k : ℕ} :
    ¬ SurvivesForever cfg π (trace cfg π g0 k) ↔
      ∃ m, k ≤ m ∧ (trace cfg π g0 m).lost cfg := by
  rw [SurvivesForever_trace_iff_forall_ge_not_lost]
  push Not
  rfl

/-- **One-step unrolling iff**: `SurvivesForever cfg π g₀ ↔
¬ g₀.lost cfg ∧ SurvivesForever cfg π (g₀.step cfg (π g₀))`. -/
theorem SurvivesForever_iff_not_lost_and_step {cfg : GameConfig}
    {π : Policy cfg} {g0 : GameState} :
    SurvivesForever cfg π g0 ↔
      ¬ g0.lost cfg ∧ SurvivesForever cfg π (g0.step cfg (π g0)) := by
  refine ⟨fun h => ⟨h.not_lost, h.step⟩, fun ⟨hnl, hstep⟩ n => ?_⟩
  match n with
  | 0 => exact hnl
  | k + 1 =>
    -- trace cfg π g0 (k+1) = trace cfg π (g0.step cfg (π g0)) k
    have htr : trace cfg π g0 (k + 1) =
        trace cfg π (g0.step cfg (π g0)) k := by
      rw [show k + 1 = 1 + k from by omega, trace_add, trace_one]
    rw [htr]; exact hstep k

/-- **Negation form of one-step unrolling**: `¬ SurvivesForever cfg π g₀
↔ g₀.lost cfg ∨ ¬ SurvivesForever cfg π (g₀.step cfg (π g₀))`. -/
theorem not_SurvivesForever_iff_lost_or_not_step {cfg : GameConfig}
    {π : Policy cfg} {g0 : GameState} :
    ¬ SurvivesForever cfg π g0 ↔
      g0.lost cfg ∨ ¬ SurvivesForever cfg π (g0.step cfg (π g0)) := by
  rw [SurvivesForever_iff_not_lost_and_step, not_and_or, Classical.not_not]

/-- **`Set.range` form of `SurvivesForever`**: equivalent to the trace
range being contained in non-lost states. -/
theorem SurvivesForever_iff_range_subset_not_lost {cfg : GameConfig}
    {π : Policy cfg} {g0 : GameState} :
    SurvivesForever cfg π g0 ↔
      Set.range (trace cfg π g0) ⊆ { g | ¬ g.lost cfg } := by
  rw [SurvivesForever_iff_forall_trace_not_lost, Set.range_subset_iff]
  rfl

/-- **Negation form**: `¬ SurvivesForever cfg π g₀` iff the trace range
meets the set of lost states. -/
theorem not_SurvivesForever_iff_range_inter_lost_nonempty {cfg : GameConfig}
    {π : Policy cfg} {g0 : GameState} :
    ¬ SurvivesForever cfg π g0 ↔
      (Set.range (trace cfg π g0) ∩ { g | g.lost cfg }).Nonempty := by
  rw [not_SurvivesForever_iff_exists_trace_lost]
  refine ⟨fun ⟨n, hn⟩ => ⟨trace cfg π g0 n, ⟨n, rfl⟩, hn⟩,
          fun ⟨g, ⟨n, hn⟩, hg⟩ => ⟨n, hn ▸ hg⟩⟩

/-- **`Disjoint` form**: `SurvivesForever cfg π g₀` iff the trace range
is disjoint from the lost-state set. -/
theorem SurvivesForever_iff_range_disjoint_lost {cfg : GameConfig}
    {π : Policy cfg} {g0 : GameState} :
    SurvivesForever cfg π g0 ↔
      Disjoint (Set.range (trace cfg π g0)) { g | g.lost cfg } := by
  rw [SurvivesForever_iff_forall_trace_not_lost, Set.disjoint_left]
  refine ⟨fun h _ ⟨n, hn⟩ hlost => h n (hn ▸ hlost),
          fun h n hlost => h ⟨n, rfl⟩ hlost⟩

/-- **`SurvivesForever` is equivalent to the existence of a safe
invariant.** Combines `safe_invariant` (reverse) with a forward
direction using `I := fun g => g ∈ Set.range (trace cfg π g0)`. -/
theorem SurvivesForever_iff_exists_invariant {cfg : GameConfig}
    {π : Policy cfg} {g0 : GameState} :
    SurvivesForever cfg π g0 ↔
      ∃ I : GameState → Prop, I g0 ∧
        (∀ g, I g → I (g.step cfg (π g))) ∧
        (∀ g, I g → ¬ g.lost cfg) := by
  refine ⟨fun h => ?_, fun ⟨I, h0, hpres, hsafe⟩ => safe_invariant I h0 hpres hsafe⟩
  refine ⟨fun g => g ∈ Set.range (trace cfg π g0), ⟨0, rfl⟩, ?_, ?_⟩
  · rintro _ ⟨n, rfl⟩
    exact ⟨n + 1, by rw [trace_succ]⟩
  · rintro _ ⟨n, rfl⟩
    exact h.trace_not_lost n

/-- **`SurvivesForever` from every state in the cycle.** Forall-packaged
form of `ClosedCycle.survives`. -/
theorem ClosedCycle.forall_mem_SurvivesForever {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    ∀ g ∈ C.states, SurvivesForever cfg C.policy g :=
  fun _ hg => C.survives hg

/-- **Uniform range bound**: every trace from a cycle state stays in
`C.states`, packaged as a forall over starting states. -/
theorem ClosedCycle.forall_mem_trace_range_subset_states {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    ∀ g ∈ C.states, Set.range (trace cfg C.policy g) ⊆ C.states :=
  fun _ hg => Set.range_subset_iff.mpr (C.trace_mem_states hg)

/-- **Uniform non-loss range**: every trace from a cycle state lies in
the non-lost set. -/
theorem ClosedCycle.forall_mem_trace_range_subset_not_lost {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    ∀ g ∈ C.states, Set.range (trace cfg C.policy g) ⊆ { g | ¬ g.lost cfg } :=
  fun _ hg => Set.range_subset_iff.mpr (C.trace_not_lost hg)

/-- **Uniform range finiteness**: every trace range from a cycle state
is finite. -/
theorem ClosedCycle.forall_mem_trace_range_finite {cfg : GameConfig}
    (C : ClosedCycle cfg) :
    ∀ g ∈ C.states, (Set.range (trace cfg C.policy g)).Finite :=
  fun _ hg => (C.states.finite_toSet).subset
    (Set.range_subset_iff.mpr (C.trace_mem_states hg))

/-- **Eventually periodic trace**: from any closed-cycle entry, there
exists a base `i` and period `d ≤ |states|` such that the trace is
periodic with period `d` for *all* future steps. Combines Tick 337
(period existence) with Tick 338 (determinism propagation). -/
theorem ClosedCycle.trace_eventually_periodic {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    ∃ i d : ℕ, 0 < d ∧ d ≤ C.states.card ∧ ∀ k,
      trace cfg C.policy g0 (i + k) =
        trace cfg C.policy g0 (i + d + k) := by
  obtain ⟨i, d, hpos, hle, heq⟩ := C.trace_exists_period h0
  refine ⟨i, d, hpos, hle, fun k => ?_⟩
  have := trace_eq_of_state_eq C.policy g0 heq k
  rw [show i + d + k = (i + d) + k from by omega]
  exact this

/-- **`d`-step periodicity by multiples**: if `trace_n = trace_(n+d)`,
then for all `j`, `trace_n = trace_(n + j*d)`. Induction on `j`. -/
theorem trace_period_multiples {cfg : GameConfig} (π : Policy cfg)
    (g0 : GameState) {n d : ℕ}
    (h : trace cfg π g0 n = trace cfg π g0 (n + d)) (j : ℕ) :
    trace cfg π g0 n = trace cfg π g0 (n + j * d) := by
  induction j with
  | zero => simp
  | succ k ih =>
    have hstep := trace_eq_of_state_eq π g0 h (k * d)
    have : n + (k + 1) * d = (n + d) + k * d := by ring
    rw [this, ← hstep]
    rw [show n + k * d = n + k * d from rfl] at ih
    exact ih

/-- **Bundled cycle field-conditions**: at any in-cycle state, the
cycle's `valid + legal_draw + not_lost + closed` properties hold
simultaneously. Useful for one-shot destructuring. -/
theorem ClosedCycle.policy_correct {cfg : GameConfig} (C : ClosedCycle cfg)
    {g : GameState} (hg : g ∈ C.states) :
    (C.policy g).Valid cfg ∧ g.bag.canDraw (C.policy g).piece ∧
      ¬ g.lost cfg ∧ g.step cfg (C.policy g) ∈ C.states :=
  ⟨C.valid g hg, C.legal_draw g hg, C.not_lost g hg, C.closed g hg⟩

/-- **Any nonempty closed cycle has at least 2 states.** From any state
`g ∈ C.states`, `g.step cfg (C.policy g)` is also in `C.states` (by
closure) and differs from `g` (by `step_ne_self`). -/
theorem ClosedCycle.states_card_ge_two {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : C.states.Nonempty) :
    2 ≤ C.states.card := by
  obtain ⟨g, hg⟩ := h
  have hclosed : g.step cfg (C.policy g) ∈ C.states := C.closed g hg
  have hne : g.step cfg (C.policy g) ≠ g :=
    GameState.step_ne_self (C.legal_draw g hg)
  have hsub : {g, g.step cfg (C.policy g)} ⊆ C.states := by
    intro x hx
    rw [Finset.mem_insert, Finset.mem_singleton] at hx
    rcases hx with rfl | rfl
    · exact hg
    · exact hclosed
  calc 2 = ({g, g.step cfg (C.policy g)} : Finset GameState).card := by
          rw [Finset.card_insert_of_notMem
                (by rw [Finset.mem_singleton]; exact (Ne.symm hne)),
              Finset.card_singleton]
    _ ≤ C.states.card := Finset.card_le_card hsub

/-- `0 < C.states.card` form for nonempty closed cycles. -/
theorem ClosedCycle.states_card_pos {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : C.states.Nonempty) :
    0 < C.states.card :=
  Finset.card_pos.mpr h

/-- `1 ≤ C.states.card` form. -/
theorem ClosedCycle.states_card_ge_one {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : C.states.Nonempty) :
    1 ≤ C.states.card :=
  C.states_card_pos h

/-- `C.states.card ≠ 0` form. -/
theorem ClosedCycle.states_card_ne_zero {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : C.states.Nonempty) :
    C.states.card ≠ 0 :=
  Nat.ne_of_gt (C.states_card_pos h)

/-- Strict `1 < C.states.card` form (Tick 533 analog). -/
theorem ClosedCycle.one_lt_states_card {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : C.states.Nonempty) :
    1 < C.states.card :=
  C.states_card_ge_two h

/-- `C.states.card ≠ 1` form. -/
theorem ClosedCycle.states_card_ne_one {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : C.states.Nonempty) :
    C.states.card ≠ 1 := by
  have := C.one_lt_states_card h
  omega

/-- A nonempty closed cycle has two distinct states. -/
theorem ClosedCycle.exists_two_distinct {cfg : GameConfig}
    (C : ClosedCycle cfg) (h : C.states.Nonempty) :
    ∃ a ∈ C.states, ∃ b ∈ C.states, a ≠ b :=
  Finset.one_lt_card.mp (C.one_lt_states_card h)

/-- **Recurrent state in a closed cycle**: there exists a base index
`n` such that the trace state at `n` is revisited arbitrarily late.
Combines Tick 337 (period exists) with Tick 340 (multiples). -/
theorem ClosedCycle.trace_recurrent {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    ∃ n : ℕ, ∀ N : ℕ, ∃ m, N ≤ m ∧
      trace cfg C.policy g0 m = trace cfg C.policy g0 n := by
  obtain ⟨n, d, hpos, _, heq⟩ := C.trace_exists_period h0
  refine ⟨n, fun N => ?_⟩
  refine ⟨n + (N + 1) * d, ?_, ?_⟩
  · have : 1 * d ≤ (N + 1) * d := Nat.mul_le_mul_right d (by omega)
    have h1 : N ≤ (N + 1) * d := by
      have : N + 1 ≤ (N + 1) * d := Nat.le_mul_of_pos_right (N + 1) hpos
      omega
    omega
  · exact (trace_period_multiples C.policy g0 heq (N + 1)).symm

/-- **Strengthening of `trace_recurrent`**: the recurrent state lies in
`C.states`. Since `trace cfg C.policy g0 m ∈ C.states` for every `m` when
`g0 ∈ C.states` (by closure of `C.policy_correct`/cycle invariants), this
specialises the recurrence witness to a state in the cycle. -/
theorem ClosedCycle.trace_recurrent_in_states {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    ∃ g ∈ C.states, ∀ N : ℕ, ∃ m, N ≤ m ∧
      trace cfg C.policy g0 m = g := by
  obtain ⟨n, hrec⟩ := C.trace_recurrent h0
  refine ⟨trace cfg C.policy g0 n, ?_, fun N => hrec N⟩
  exact C.trace_mem_states h0 n

/-- **Existence of a recurrent cycle state**: any nonempty closed cycle
contains a state that the trace returns to arbitrarily late. Strips the
`g0` parameter — useful as a pure-existence cycle property. -/
theorem ClosedCycle.exists_recurrent_state {cfg : GameConfig}
    (C : ClosedCycle cfg) (hne : C.states.Nonempty) :
    ∃ g ∈ C.states, ∃ g0 ∈ C.states, ∀ N : ℕ, ∃ m, N ≤ m ∧
      trace cfg C.policy g0 m = g := by
  obtain ⟨g0, hg0⟩ := hne
  obtain ⟨g, hg, hrec⟩ := C.trace_recurrent_in_states hg0
  exact ⟨g, hg, g0, hg0, hrec⟩

/-- **Cycle ⇒ Survival forever from a recurrent state.** From a nonempty
closed cycle, there is at least one cycle state `g` from which the
cycle's policy survives forever. Combines `exists_recurrent_state`
(or just nonemptiness) with `survives`. -/
theorem ClosedCycle.exists_state_survivesForever {cfg : GameConfig}
    (C : ClosedCycle cfg) (hne : C.states.Nonempty) :
    ∃ g ∈ C.states, SurvivesForever cfg C.policy g := by
  obtain ⟨g, hg⟩ := hne
  exact ⟨g, hg, C.survives hg⟩

/-- **Pure existence of a forever-surviving (policy, state) pair from a
nonempty cycle.** Drops the cycle parameter from the witness — useful
when only the (policy, state) pair is wanted downstream. -/
theorem ClosedCycle.exists_policy_survivesForever {cfg : GameConfig}
    (C : ClosedCycle cfg) (hne : C.states.Nonempty) :
    ∃ π : Policy cfg, ∃ g : GameState, SurvivesForever cfg π g := by
  obtain ⟨g, _, hsurv⟩ := C.exists_state_survivesForever hne
  exact ⟨C.policy, g, hsurv⟩

/-- **M2 → infinite play (existence form):** existence of a nonempty
closed cycle implies existence of a (policy, state) pair that
survives forever. -/
theorem exists_policy_survivesForever_of_exists_nonempty_cycle
    {cfg : GameConfig}
    (h : ∃ C : ClosedCycle cfg, C.states.Nonempty) :
    ∃ π : Policy cfg, ∃ g : GameState, SurvivesForever cfg π g := by
  obtain ⟨C, hne⟩ := h
  exact C.exists_policy_survivesForever hne

/-- **`Set.range` form**: the trace from a cycle state stays in
`C.states`. -/
theorem ClosedCycle.trace_range_subset_states {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    Set.range (trace cfg C.policy g0) ⊆ C.states :=
  Set.range_subset_iff.mpr (C.trace_mem_states h0)

/-- **`Set.range` form for non-loss**: no trace state from a cycle
state is lost. -/
theorem ClosedCycle.trace_range_subset_not_lost {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    Set.range (trace cfg C.policy g0) ⊆ { g | ¬ g.lost cfg } :=
  Set.range_subset_iff.mpr (C.trace_not_lost h0)

/-- **Trace range is finite.** Since the trace range is contained in
the finite set `C.states`, it is itself finite. -/
theorem ClosedCycle.trace_range_finite {cfg : GameConfig}
    (C : ClosedCycle cfg) {g0 : GameState} (h0 : g0 ∈ C.states) :
    (Set.range (trace cfg C.policy g0)).Finite :=
  (C.states.finite_toSet).subset (C.trace_range_subset_states h0)

end Tetris
