[package]
name = "tetris-game"
version = "0.1.0"
edition = "2024"
authors = ["Alex Comerford <alex@taoa.io>"]
publish = false

[lib]
name = "tetris_game"
path = "src/lib.rs"

[features]
default = []
never-inline = []

[dependencies]
rand.workspace = true
proc-macros.workspace = true
tetris-utils.workspace = true

[lints]
workspace = true
