version: "3.7"

services:
  tetris_atlas_dev:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ..:/workspace:Z
    network_mode: 'host'
    entrypoint: sleep infinity
